      - name: Test API with curl (debug)
        run: |
          set -e
          curl -sS -o api.json -w "HTTP:%{http_code}\n" "https://brsapi.ir/Api/Market/Gold_Currency.php?key=BSKDtB7FB31bcKKZgegXzfzLKQ2abZ5G"
          echo "api.json size: $(stat -c%s api.json) bytes"
          head -c 300 api.json || true

      - name: Fetch API Data (action)
        id: fetch
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: "https://brsapi.ir/Api/Market/Gold_Currency.php?key=BSKDtB7FB31bcKKZgegXzfzLKQ2abZ5G"
          configuration: '{ "method": "GET" }'

      - name: Inspect action output
        run: |
          ls -la fetch-api-data-action || true
          if [ -s "fetch-api-data-action/data.json" ]; then
            head -c 300 fetch-api-data-action/data.json
          else
            echo "ACTION MISSING OUTPUT" >&2; exit 1
          fi
